### ISSUE TITLE
ZAP Tool generates not compiling code

### ISSUE THREAD

**Issue by eve-cxrp** [project-chip/zap#135] opened 2021-04-20 06:55 UTC
Hi,

I'm trying to generate a cluster with:

- Binary Input
- Percentage Remaining 
- Identify

The generated code for the binary input is not compiling. It also looks very strange:

In callback.h:
```
/** @brief Binary Input (Basic) Cluster Init
 *
 * Cluster Init
 *
 * @param endpoint    Endpoint that is being initialized
 */
void emberAfBinaryInput(Basic) ClusterInitCallback(chip::EndpointId endpoint);
```

and in gen_config.h:

```
// Use this macro to check if the server side of the Binary Input (Basic) cluster is included
#define ZCL_USING_BINARY_INPUT_BASIC_CLUSTER_SERVER
#define EMBER_AF_PLUGIN_BINARY_INPUT_(_BASIC_) _SERVER
#define EMBER_AF_PLUGIN_BINARY_INPUT_(_BASIC_)
```

Some compiler error output related to this code snippets:

```
../src/gen/gen_config.h:48: warning: "EMBER_AF_PLUGIN_BINARY_INPUT_" redefined
   48 | #define EMBER_AF_PLUGIN_BINARY_INPUT_(_BASIC_)
      | 
../src/gen/gen_config.h:47: note: this is the location of the previous definition
   47 | #define EMBER_AF_PLUGIN_BINARY_INPUT_(_BASIC_) _SERVER
```
and 

```
In file included from ../src/gen/call-command-handler.cpp:25:
../src/gen/callback.h:56:30: error: variable or field 'emberAfBinaryInput' declared void
   56 | void emberAfBinaryInput(Basic) ClusterInitCallback(chip::EndpointId endpoint);
      |                              ^
../src/gen/callback.h:56:25: error: 'Basic' was not declared in this scope
   56 | void emberAfBinaryInput(Basic) ClusterInitCallback(chip::EndpointId endpoint);
```

Here is also the used file for the generation: [config.zap.txt](https://github.com/project-chip/zap/files/6341302/config.zap.txt)

**Comment by LuDuda** [comment] 2021-04-21 10:46
It seems that the problem is caused by the `name` property set to `Binary Input (Basic)` - please note the parenthesis.

During the generation of the [code](https://github.com/project-chip/connectedhomeip/blob/4f0ade5fcd50f99f53188ec401e18c2a22f47e14/src/app/zap-templates/templates/app/callback.zapt#L33) the `asCamelCased` method is used, and as a result, the electron's `toCamelCase` method is called [here](https://github.com/project-chip/zap/blob/74c34f59092a9e593a4826dc657e41f85859ea55/src-electron/util/string.js#L29). As you can see below, this method does not remove `(` or `)` characters which result in building errors afterwards.

![image](https://user-images.githubusercontent.com/5144764/115540744-9e578380-a29e-11eb-884a-40259bc44bff.png)

The quick workaround might be to change the `name` property. But for the future, I wonder if we should ignore parenthesis - @tecimovic.

**Comment by wehale** [comment] 2021-04-21 15:09
We should fix this to ignore the parenthesis, I'll talk to @tecimovic about this fix

**Comment by tecimovic** [comment] 2021-04-23 01:58
I'll take a look. Thanks for debugging this issue already, @LuDuda !

**Comment by markus-becker-tridonic-com** [comment] 2021-05-03 10:12
Ampersand (&) should also be on the ignore list. Example which is not yet in any of the XMLs:
`#define EMBER_AF_PLUGIN_LUMINAIRE_DIAGNOSTICS_ &_MAINTENANCE`

**Comment by tecimovic** [comment] 2021-05-13 11:59
PR has been merged. Please close the issue after retesting.

**Closed** 2021-05-20 05:50 UTC
