### ISSUE TITLE
ZAP generation time is too high (>500 seconds)

### ISSUE THREAD

**Issue by thevamad** [project-chip/zap#828] opened 2022-11-21 14:50 UTC
!MESSAGE Job found still running after platform shutdown.  Jobs should be canceled by the plugin that scheduled them during shutdown: com.silabs.ss.framework.uc.internal.generation.UcThreadingGenerator$UcProjectGenerationTask
Generation issue: Follow-up generation did not complete within 500 seconds!

**Comment by tecimovic** [comment] 2022-11-21 15:11
To get some numbers, on my Linux box, the timing currently is:

```
time npm run gen
```
ends with:
```
🕐 Generation time: 45s 872ms 
    ✍  Result: tmp/genResult.json
😎 All done: 51s 622ms.

real	0m51.919s
user	0m57.844s
sys	0m2.417s
```

and doing:
```
time npx jest test/gen-zigbee-1.test.js
```
results in:
```
Test Suites: 1 passed, 1 total
Tests:       13 passed, 13 total
Snapshots:   0 total
Time:        310.733 s, estimated 360 s
Ran all test suites matching /test\/gen-zigbee-1.test.js/i.

real	5m12.109s
user	6m43.300s
sys	0m16.079s
```

Terrible.

**Comment by brdandu** [comment] 2022-11-21 15:52
> !MESSAGE Job found still running after platform shutdown. Jobs should be canceled by the plugin that scheduled them during shutdown: com.silabs.ss.framework.uc.internal.generation.UcThreadingGenerator$UcProjectGenerationTask
> Generation issue: Follow-up generation did not complete within 500 seconds!

@thevamad could you also add some steps for a reproducer so that we can replicate the issue on our end?

**Comment by brdandu** [comment] 2023-01-30 15:26
I think we can close this. This might have happened because the CI machine might be overloaded.

**Closed** 2023-03-28 17:03 UTC
Labels: high priority
