### ISSUE TITLE
Meta package behaves strangely

### ISSUE THREAD

**Issue by tecimovic** [project-chip/zap#1077] opened 2023-07-19 19:48 UTC
1.) Run `npm run zapall` (on latest master, after zapall was changed to use 3 packages).
2.) See this page:
![image](https://github.com/project-chip/zap/assets/7923190/cd04ed2e-1193-4f2d-bd88-26626211b152)
3.) Select the third package "Unit Test Meta-Data".
4.) Observe how everything changes into "Matter", even though this package is NOT matter.
5.) Then create a new endpoint: notice how this does NOT allow you to pick no device type.
6.) There is NO WAY I can get to selection of clusters. There are some clusters in that meta package, but I simply can't get to them.

**Comment by paulr34** [comment] 2023-09-07 20:26
[
<img width="1598" alt="Screenshot 2023-09-07 at 4 26 02 PM" src="https://github.com/project-chip/zap/assets/64710345/c5c3feb0-9474-4480-95c5-7106a66de80c">
](url)

**Comment by paulr34** [comment] 2023-09-07 20:26
@tecimovic I am closing this because I could not reproduce.

**Closed by paulr34** 2023-09-07 20:26 UTC
