### ISSUE TITLE
Zap endpoint information

### ISSUE THREAD

**Issue by Mehradml** [project-chip/zap#553] opened 2022-06-14 10:06 UTC
In the endpoint section, the shown summary of all endpoints is linked into one and when you change the selected endpoint, the summary information of all endpoints changes.

**Comment by brdandu** [comment] 2023-01-30 16:35
This is linked to the removal of endpoint summary from all endpoint panes. Closing this as a duplicate of https://github.com/project-chip/zap/issues/725 now.

**Closed by brdandu** 2023-01-30 16:35 UTC
