### ISSUE TITLE
Changing device type breaks attribute reportability

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/zap#996] opened 2023-04-17 15:49 UTC
STEPS TO REPRODUCE:

1. In the Matter repo (as of SHA `533f84c9fcce035dd23167128fc89a6901c79274`), run `./scripts/tools/zap/run_zaptool.sh examples/lighting-app/lighting-common/lighting-app.zap`
2. Examine the "Attribute Reporting" view of the "On/Off" cluster on endpoint 1, and see that all attributes are set as reportable.
3. Edit endpoint 1 and change the device type from "Matter Dimmable Light (0x0101)" to "Matter Extended Color Light (0x010D)".  Click the "SAVE" button.
4. Examine the "Attribute Reporting" view of the "On/Off" cluster on endpoint 1, and see that all the non-global attributes are no longer set as reportable.

Similarly, if I just add a new endpoint with device type "Matter Extended Color Light (0x010D)" then all the "On/Off" non-global attributes are set to not reportable in the new endpoint's automatically-enabled "On/Off" cluster.

For comparison, if I create an endpoint with device type "Matter Door Lock (0x000A)" and then enable the "On/Off" cluster (not enabled by default) on that endpoint, then the non-global attributes are correctly (due to Matter SDK defaults) marked as reportable.

@brdandu @tecimovic

**Comment by paulr34** [comment] 2023-04-24 21:33
![Screenshot 2023-04-24 at 5 27 52 PM](https://user-images.githubusercontent.com/64710345/234120904-f2305ce9-1f8c-4150-8f8f-dd3618de8343.png)
 ^Above is the On/Off cluster for **MA-extendedcolorlight** and below is the On/Off for **Matter On/Off Light Switch**
![Screenshot 2023-04-24 at 5 30 11 PM](https://user-images.githubusercontent.com/64710345/234121212-c3d43281-ad80-4338-ac86-b8d893c3958d.png)

This further leads me to believe that the problem is the device type configuration in this xml file. 

Additionally, I did find an example of non global attribute reporting being enabled by default. Note that it is "DEVICE_TYPE". I am still investigating why that happens. 
<img width="1447" alt="Screenshot 2023-04-24 at 4 13 59 PM" src="https://user-images.githubusercontent.com/64710345/234121463-4475938a-dba8-40e9-8cdb-eb5ab8ce00b0.png">

Any feedback is welcome

**Comment by bzbarsky-apple** [comment] 2023-04-25 19:39
> because for it to be enabled by default it must be specified in that XML file.

Wait, why?  If reporting is not specified in the XML file, the SDK default should be used, which for matter is "reporting enabled".

**Comment by paulr34** [comment] 2023-04-25 19:57
Even if attribute reporting is listed "mandatory", it still does not turn on because the toggle is using a different list of true and false values because it cannot take in string values. The list of true and false values are out of sync with the "mandatory" setting. 

An easy fix would be to iterate through the list and set true whenever an attribute reporting is "mandatory" but ideally I would want it to work in a similar fashion as when a user enables it manually. 

I at least want to understand how that works before I do anything.

**Comment by paulr34** [comment] 2023-09-07 20:33
fixed , see merged PR

**Closed by paulr34** 2023-09-07 20:33 UTC
Labels: matter
